### ISSUE TITLE
Switch docker to docker.io and docker-compose to pip

### ISSUE THREAD

**Issue by iancleary** [iancleary/ansible-role-docker#13]

**Comment by iancleary** [comment]
```yaml
- name: Install python3 pip
  become: true
  ansible.builtin.apt:
    name: python3-pip

- name: Install python packages
  ansible.builtin.pip:
    name: 
      - docker==6.0.0
      - docker-compose==1.29.2
      - PyYAML
```
